danielaparker/jsoncons

src/jsoncons/json_reader.hpp

Compiling a code includes `basic_json::parse_string()` with `g++ -Wall -std=gnu++11`, I got "unused variable" warning as follow:
jsoncons/json_reader.hpp: In instantiation of ‘void jsoncons::basic_json_reader<Char>::parse() [with Char = char]’:
jsoncons/json_reader.hpp:395:5:   required from ‘void jsoncons::basic_json_reader<Char>::read() [with Char = char]’
jsoncons/json2.hpp:1105:5:   required from ‘static jsoncons::basic_json<Char, Alloc> jsoncons::basic_json<Char, Alloc>::parse_string(const std::basic_string<_CharT>&) [with Char = char; Alloc = std::allocator<void>]’
jsoncons/json_reader.hpp:502:28: warning: unused variable ‘count1’ [-Wunused-variable]

Fixed unused-variable warning in basic_json::parse().

---

src/jsoncons/json_reader.hpp
src/jsoncons/parse_error_handler.hpp
test_suite/src/json_parse_tests.cpp

Various bits of code assume the top-level value in a JSON string is an
object or an array; however, if this is not the case, it is not caught
as a parse error. This introduces the error code expected_container.
See issue #32.

Generate parse errors if the top-level value is not object or array.

---

src/jsoncons/json_structures.hpp
test_suite/src/json_checker_tests.cpp
test_suite/src/json_equals_tests.cpp

#26 fixed one bug with operator== on json objects, but created another, because I didn't think through the behaviour of std::lower_bound properly.
This pull also includes an unrelated commit that makes the test suite build (did you fail to commit json_parser.hpp?)

Object equals

---

src/jsoncons/jsoncons_config.hpp

Visual Studio 2015 added proper noexcept support, as a result the noexcept specification needs to be updated for jsoncons to build without error.

Fixed the noexcept specification for Visual Studio 2015

---

src/jsoncons/json_parser.hpp

The template parameter in the class overrode the parameter on the members, this change renames the member parameter.

Fix issue compiling with clang where template parameters override each other

---

src/jsoncons/json_structures.hpp

This is a workaround for a [C++11 issue in GCC 4.8](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54577) (NB: GCC 4.8 is shipped with Ubuntu 14.04 LTS, which is likely to be used by a lot of companies for a little while yet).

GCC 4.8 workaround

---

src/jsoncons/json.hpp
test_suite/build/cmake/.gitignore
test_suite/src/json_equals_tests.cpp

Currently, `json() == json(json::object())` evaluates to false, which is not what you would expect from the documentation. This fixes that.

Fix default constructor

---

test_suite/src/jsonpath/jsonpath_filter_tests.cpp
test_suite/src/jsonpath/jsonpath_tests.cpp

The tests that depend on <regex> support are marked as expected failures when compiling with GCC 4.8.
This is the "ignore it" approach for #72.

Allow for broken regex with GCC 4.8 in unit tests

---

src/jsoncons/jsoncons_io.hpp

This fixes "comparison of signed and unsigned types" error. Should be safe from the code (`len` never becomes smaller than 1).

Fix len type

---

src/jsoncons/json_filter.hpp
src/jsoncons/osequencestream.hpp
test_suite/src/json_extensibility_tests.cpp
test_suite/src/json_type_traits_container_tests.cpp

This allows tests to build without warnings or errors on GCC 6 and Clang 3.8.

Fix compilation errors and warnings by GCC and Clang

---

src/jsoncons/json_type_traits.hpp

`std::array` doesn't have construction from iterators. Because of that, we need to add separate support for it to be able to deserialize.

Add read support for std::array

---

src/jsoncons_ext/jsonpath/json_query.hpp

Allows to apply filter expression over a single object. A single object might be considered as one-element array.
For example:
{
"header": {
"type": "A"
}
}
The json-path expression "$.header[?(@.type == 'A')] allows to filter headers of type "A".

Filter objects extension

---

.travis.yml
src/jsoncons/json.hpp
src/jsoncons/unicode_traits.hpp
test_suite/build/cmake/CMakeLists.txt

Also enable tests on Travis for this mode so this won't go unnoticed again, and fix style warnings of new GCC (about misleading identation).

Fix broken JSONCONS_NO_DEPRECATED

---

src/jsoncons/json.hpp
src/jsoncons/json_parser.hpp
src/jsoncons/unicode_traits.hpp

GCC 7 now warns if case fallthru is used without a marker (either C++17 attribute or a comment).

Fix GCC 7 warnings

---

src/jsoncons/json.hpp
test_suite/src/json_equals_tests.cpp

In case one compares a string against something else for equality, the right
hand side was unconditionally converted to a string_view.
This change ensures that the right hand side is a string.

Fix equality check of strings

---

include/jsoncons/json_parser.hpp

while it works without any problem on gcc or clang, I have many problems with the "minus" label (json_parser.hpp) in Visual Studio, causing a name clash with std::minus (without ever using the std namespace)
If you know any better workaround, please let me know

avoid clash with std::minus in VS2017

---

include/jsoncons/json.hpp

json_decoder fails to compile when using a custom allocator, because it tries to copy string types which use mismatching allocators.
Now that could be fixed differently if the json output is really meant to offer std::allocator only, but that is probably not desired, because a user naturally expects the out values with the specified allocator.

Fix compile error from using custom allocator

---

include/jsoncons_ext/csv/csv_parser.hpp

std::istringstream does not take a std::string_view (vs 2017)

Fix compile error from using JSONCONS_HAS_STRING_VIEW

---

include/jsoncons/json_type_traits.hpp

Fails to compile with c++17 string_view

Fix compile error in json_type_traits for string types

---

include/jsoncons_ext/csv/csv_parser.hpp

Hello Daniel, thanks for an awesome project.
I have an issue with the new type inference mechanism. In a csv file I have long hexadecimal strings which might not contain chars from 'a' to 'f', e.g. `4000001600010001000000000300000000000008000000010100`.
Since there are only digits in the field, the csv parser interprets these values as an integer, gets an overflow and falls back to double, which in turn leads to the information loss due to the double's finite precision, e.g. you might get back something like `4000001600010000762621119870936895770498791553105920.000000`.
I propose to fall back to string type by default.

Use string as inferred type for overflow integers

---

include/jsoncons/binary/binary_utilities.hpp

Spotted by Prof Brian Ripley <ripley@stats.ox.ac.uk>

Use double type for 1st argument to ldexp()

---

include/jsoncons/bignum.hpp
include/jsoncons/json.hpp

Hi,
I discovered this project due to its inclusion in [miloyip/nativejson-benchmark](https://github.com/miloyip/nativejson-benchmark).  I locally updated its submodule for jsoncons from commit 88194db to the latest master.  After adjusting the tests to the current API, the benchmark segfaulted due to a stack overflow during the conformance testing.
Long story short, with the help of gdb, I found a case where conversion of `basic_json` values backed by bignums to primitive types entered an infinite recursion -- for example, `as_double()` parses the string representation of the value, expecting it to convert to a double, but its data type remains a string because it is semantically a bignum and too big to fit in a double.  I fixed this by using `as_bignum()` and a conversion operator if the …

Fix infinite recursion with bignums and misc. undefined behavior

---

include/jsoncons/json_exception.hpp
third_party/catch/catch.hpp

these macroses are generates a literal constants that contains full file names and after that the release exe file contains these literal constants with my local directories structure.
so it should be removed from release build and looks  the JSONCONS_ASSERT macros also may be fully removed from release but I don't sure.
let me know if You have any question
thanks for this cool library.

__FILE__ and __LINE__ macroses removed from release version

---

CMakeLists.txt

Currently only `include/jsoncons` directory is being copied to installation place.
Add `include/jsoncons_ext` as well.

Include jsoncons_ext directory into installation script

---

include/jsoncons/json_type_traits.hpp

The multi-line comment at 1151 is not necessary and causes builds that treat warnings as errors to fail.

removed a multi-line comment

---

include/jsoncons/json_exception.hpp

GCC 9.2 produces warning: `‘class jsoncons::json_exception’ has virtual functions and accessible non-virtual destructor`

Fix compiler (gcc 9.2) warning "accessible non-virtual destructor"

---

doc/ref/csv/basic_csv_options.md

The mapping `n_columns` does not exist.

Fix incorrect default mapping with headers in docs.

---

fuzzers/build_fuzzers.sh

I am starting to move the content we have on the OSS-Fuzz repo into the main jsoncons repo so we don't have to update OSS-Fuzz everytime we change contents in here. This is the first step.

Migrating OSS-Fuzz content to upstream

---

include/jsoncons/config/compiler_support.hpp

strtolod_l/wcstold_l are only supported when building for Android SDK level 21 and above. Bulding for min SDK less than 21 results in a compile error in parse_number.hpp.

Don't define JSONCONS_HAS_STRTOLD_L for ANDROID_API < 21

---

include/jsoncons/config/compiler_support.hpp

It was clearly a copy-paste error to define them as BOOST_HAS_FLOAT128,
especially as later code checks for JSONCONS_HAS_FLOAT128.
Fixes #272

Fix float128 feature macro names

---

include/jsoncons/json_reader.hpp

Hello,
Fixing this compilation issue. gcc 11 does not accept this wrong constructor declaration anymore.
```
In file included from BUILD/jsoncons-0.157.2/include/jsoncons/basic_json.hpp:35,                                                                                                                                           from BUILD/jsoncons-0.157.2/include/jsoncons/json.hpp:10,
from BUILD/jsoncons-0.157.2/tests/src/JSONTestSuite_tests.cpp:13:
BUILD/jsoncons-0.157.2/include/jsoncons/json_reader.hpp:37:47: error: expected unqualified-id before 'const'
37 |     json_utf8_to_other_visitor_adaptor<CharT>(const json_utf8_to_other_visitor_adaptor<CharT>&) = delete;
|                                               ^~~~~
BUILD/jsoncons-0.157.2/include/jsoncons/json_reader.hpp:37:47: error: …
```

Fix compilation error with gcc 11

---

doc/ref/jsonpath/json_replace.md
examples/src/jsonpath_examples.cpp
include/jsoncons/detail/more_type_traits.hpp
include/jsoncons_ext/jsonpath/json_query.hpp

This makes it possible to change values depending on their previous values.
With json_replace() it is possible to replace a matched value with a new predefined value but it is not possible to rewrite the value depending on the previous value.
Getting the pointers of the matched values allows us to run search-and-replace rules on the old value to generate the new value.

variant of json_query() that returns pointers

---

include/jsoncons/allocator_holder.hpp
include/jsoncons/json_container_types.hpp
tests/src/json_object_tests.cpp

While trying to use this library I ran into this issue, the copy/move constructor are implemented however the `operator=` where not present or deleted in the top level object. They are however implemented throughout the code back such as:
https://github.com/danielaparker/jsoncons/blob/b9e95d6a0bcb2dc8a821d33f98a530f10cfe1bc0/include/jsoncons/json_container_types.hpp#L416
https://github.com/danielaparker/jsoncons/blob/b9e95d6a0bcb2dc8a821d33f98a530f10cfe1bc0/include/jsoncons/json_container_types.hpp#L426
Perhaps there is a reason but looking at the git blame there was no obvious reason why but feel free to enlighten me 🤓 
I also noticed they are missing from the `json_array` which might be something to considered in the future!

add missing copy/move assignment operators to json_object

---

doc/ref/json_type_traits/custom-specializations.md

The current documentation [`Custom specialization`](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/json_type_traits/custom-specializations.md#custom-specialization) is wrong and the example showing how to specialize a custom class to support `json_type_traits` fails to compile because the wrong macro is used.

Fix incorrect custom-specializations.md docs

---

include/jsoncons_ext/jsonpath/path_expression.hpp

There is a memory leak in node_set when it holds only one node.

Fix memory leak in jsoncons::jsonpath::node_set

---

include/jsoncons_ext/jsonpath/path_expression.hpp

We get warnings when compiling the jsonpath extension:
`... has accessible non-virtual destructor [-Wnon-virtual-dtor]`
Simply defining a defaulted virtual destructor for the base class `binary_operator` removes the warning.

Get rid of gcc warning -Wnon-virtual-dtor

---

CMakeLists.txt

downside is that it at least requires cmake 3.14
closes #322

Add ARCH_INDEPENDENT so the generated cmake config files are really arch independent

---

include/jsoncons/json_container_types.hpp

This is used by jsoncons::type_traits::detail::basic_json_t in certain
circumstances, and ICC does not like that it is not publicly accessible.
Fixes compilation errors like:
```
jsoncons/basic_json.hpp(49): error #525: type "jsoncons::json_object<KeyT, Json, std::enable_if<std::is_same<Json::implementation_policy::key_order, jsoncons::sort_key_order>::value, void>::type>::implementation_policy [with KeyT=std::basic_string<char, std::char_traits<char>, std::allocator<char>>, Json=jsoncons::basic_json<char, jsoncons::sorted_policy, std::allocator<char>>]" (declared at line 541 of "jsoncons/json_container_types.hpp") is an inaccessible type (allowed for cfront compatibility)
basic_json_t = basic_json<typename T::char_type,typename T::implementation_policy,typename T::allocator_type>; …
```

Make implementation_type public in container types

---

.github/workflows/codeql-analysis.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
.github/workflows/windows.yml.bak

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

doc/Tutorials/Custom Allocators.md
doc/ref/basic_json.md
examples_boost/interprocess_allocator/shared_memory.cpp
examples_boost/interprocess_allocator2/shared_memory.cpp
include/jsoncons/basic_json.hpp

Fixes #392.
All tests ran and passe with success.
Boost examples now compile and produce expected output.

Fix boost interprocess example

---

include/jsoncons/json_parser.hpp

Fixed behaviour:
When the `json_parser::update()` function is called multiple times (streaming) the parsing position is calculated incorrectly when parsing strings.
This behaviour is also observable with the function `ser_context::column()`
See test program: https://gist.github.com/wbangna/12c348fbf30b1bc89ccc6a3ba807268d

bugfix: The parsing position is incorrect, when updating multiple times

---

include/jsoncons/config/compiler_support.hpp
include/jsoncons/config/jsoncons_config.hpp
include/jsoncons/detail/parse_number.hpp
include/jsoncons/json_options.hpp
include/jsoncons_ext/csv/csv_parser.hpp
test/corelib/src/json_options_tests.cpp
test/corelib/src/wjson_tests.cpp
test/csv/src/csv_tests.cpp

Fixes #403 #404 #405.
> I changed the CSV parser code to no longer call `substr`; that allowed compilation and tests to pass.
Thanks. Interesting observation about `substr`.
Regarding the remaining failure, I wouldn't expect the test to work with gcc 4.8, as gcc 4.8 `basic_string` had issues with stateful allocators. It's probably enough to suppress the test if 
```
(defined(__GNUC__) && (__GNUC__ == 4) && __GNUC_MINOR__ < 9))
```

Multiple fixes for float parsing and boolean pretty print with wjson

---

include/jsoncons_ext/jsonpath/jsonpath_expression.hpp

The Function `jsonpath_expression::evaluate()` should be `const`.

mark jsonpath_expression::evaluate() as const

---

include/jsoncons/config/compiler_support.hpp
include/jsoncons/staj_iterator.hpp

- add `defined()` for `__EXCEPTIONS` and `_MSC_VER` in compiler_support.hpp (see https://github.com/peetonn/ROSBridge2Unreal/commit/cfe4a89451039a4f680fc41c722cf85afd62b131)
- remove shadowing of `using char_type = typename Json::char_type;` in stat_iterator.hpp

Fix macOS build

---

include/jsoncons_ext/jsonpath/expression.hpp

This is to resolve issue #432 
- Switched hash struct to use std::uintmax_t instead of std::size_t and long long

Compilation warning in win32 configuration due to down cast

---

include/jsoncons/json_options.hpp

I stumbled on this, while trying out jsoncons.  
I got the compile error:
```
/home/meierfra/devel/test/jsonconsTest/jsoncons/include/jsoncons/json_options.hpp: In instantiation of ‘jsoncons::basic_json_decode_options<CharT>::basic_json_decode_options(jsoncons::basic_json_decode_options<CharT>&&) [with CharT = char]’:
/home/meierfra/devel/test/jsonconsTest/main.cpp:31:65:   required from here
/home/meierfra/devel/test/jsonconsTest/jsoncons/include/jsoncons/json_options.hpp:374:102: error: ‘class jsoncons::basic_json_decode_options<char>’ has no member named ‘default_json_parsing’
374 |         : super_type(std::move(other)), lossless_number_(other.lossless_number_), err_handler_(other.default_json_parsing())
| …
```

fix basic_json_decode_options constructor

---

include/jsoncons/basic_json.hpp

After updating to 0.171.0, our code failed to compile with the following error:
`.../jsoncons/basic_json.hpp:3866:13: error: no matching member function for call to 'dump_pretty' dump_pretty(cont, options, indent, ec);`
The error occurs because on line 3866, dump_pretty is called with 4 parameters, but a dump_pretty function with the corresponding signature does not exists. After looking into the issue (and reading the doc https://github.com/danielaparker/jsoncons/blob/master/doc/ref/corelib/json/dump.md), I think that a dump_pretty function that takes an indent parameter should not exist at all.
I am not entirely sure how to fix this. The docs say that there should be a dump_pretty function that takes a CharContainer and options, with the options having a default parameter. My …

Change signature of dump_pretty

---

include/jsoncons_ext/jsonpath/expression.hpp

Fixes the warning about declaration shadows a local variable for path parameter.

Fix for shadowed path variable

---

include/jsoncons_ext/jsonpath/json_query.hpp

Fixes the warning about declaration shadows a local variable for path parameter.

Fix for shadowed path variable for JSON Query

---

include/jsoncons_ext/jsonschema/json_validator.hpp

Default error reporter in jsonschema prints only ```o.message()``` which only shows the reason.  I think it is not enough. Users cannot know where the error occurs. Many other json schema libraries aim for human-comprehensible error messages.
So, how about print little bit more detail? I simply modified by adding ```o.instance_location()``` , referred from custom error reporter example in jsonschema doc.

jsonschema: print validation error location for default error reporter

---

include/jsoncons/detail/heap_string.hpp

fix: avoid over-allocating memory for 8 byte alignment or less

---

include/jsoncons/json_object.hpp
include/jsoncons_ext/cbor/cbor_parser.hpp
test/corelib/src/detail/span_tests.cpp

I've managed to get #507 working with llvm-toolset-7 on CentOS 7. Unfortunately, I can't move to devtoolset-9 as it was done in the original issue.

Centos7 build fix

---

test/CMakeLists.txt

Hello
I ran into a path-related issue with `ctest` in a project that fetches `jsoncons`.
The issue can be reproduced with the following `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.25)
project(test_jsoncons)
include(FetchContent)
FetchContent_Declare(jsoncons
GIT_REPOSITORY https://github.com/danielaparker/jsoncons.git
GIT_TAG v0.176.0
)
FetchContent_MakeAvailable(jsoncons)
enable_testing()
```
Then we can run the following commands:
```shell
% cmake -S . -B build -G Ninja
% cd build
% ninja 
% ctest  
Test project /home/pierre/temp/test_jsoncons/build
Start 1: unit_tests
Failed to change working directory to /home/pierre/temp/test_jsoncons/test : No such file or directory
1/1 Test #1: unit_tests .......................***Not Run   0.00 sec
0% tests passed, 1 tests failed …
```

Fix WORKING_DIRECTORY for unit tests

---

include/jsoncons/uri.hpp

This was showing up as a heap-buffer-overflow during `operator==`, after calling [this constructor](https://github.com/danielaparker/jsoncons/blob/232e16239fe930e1b5bb13cecd5510abbb6107d5/include/jsoncons/uri.hpp#L109-L113)

uri::parse: Fix offset of query_

---

include/jsoncons/json_parser.hpp

In Kvrocks we faced an integer overflow detected by UBSAN in basic_json_parser.
```
/home/runner/work/kvrocks/kvrocks/build/_deps/jsoncons-src/include/jsoncons/json_parser.hpp:180:74: runtime error: signed integer overflow: 2147483647 + 2 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/runner/work/kvrocks/kvrocks/build/_deps/jsoncons-src/include/jsoncons/json_parser.hpp:180:74 in 
```
The reason is that we set `max_nesting_depth` to `numeric_limits::max()`, so that `max_nesting_depth + 2` leads to overflow.
Here I use an equivalent form to eliminate the problem.

Avoid integer overflow UB in basic_json_parser

---

include/jsoncons_ext/jmespath/jmespath.hpp

Unexpected behavior `join`，when elements are empty strings ahead of the json array. For example: `join(',', @)` 
---
["", "", "a", "","b", "c", ""]
---
current result is:
```
a,,b,c,
```
but expected:
```
,,a,,b,c,
```

unexpected behavior for built-in function `join` of  jmespath

---

examples/build/cmake/CMakeLists.txt
examples/build/cmake/README.txt

the path ../../../build/ was not accessible for the CMakeLists in examples, so making it to ../../build.
Suggested to add config files in examples/build/cmake/README as the cmake is expecting those files.

fixing the path for config files

---

examples/build/cmake/CMakeLists.txt
examples_boost/serialization_examples.cpp

- Changed serialization_examples.cpp to use boost to output type _int128, And run chinese_uchar8_t only when __cpp_char8_t is defined.
- Changed CmakeLists to create separate executables for each source file, as it is not possible to compile all the files into single executable because of conflict due to multiple main functions.
With this transaction the example sources except "json_traits_macros_examples.cpp" can be compiled without errors just following instructions in  "jsoncons/examples/build/cmake/README.txt".  
Will try to fix json_traits_macros_examples.cpp in future, but for now removing this file and doing cmake would give separate executables for all the examples.

Fixing example files compilation

---

examples/src/jmespath_customer_functions_examples.cpp
include/jsoncons_ext/jmespath/jmespath.hpp
test/jmespath/input/compliance/functions.json

1. fix a bug of avg function. 
2. add customer functions to enhance the processing capabilities of jmespath extension.(I just tested the example on Ubuntu 22.04.)
3. fix a bug of jmespath test (function expression `"not_null()"` with no args, should result `null` instead of invalid-arity error)

add customer functions for `jmespath`

---

include/jsoncons/text_source_adaptor.hpp

```
external/jsoncons~/include/jsoncons/text_source_adaptor.hpp:84:15: error: redefinition of 'value_type'
--
  | using value_type = typename Source::value_type;
  | ^
  | external/jsoncons~/include/jsoncons/text_source_adaptor.hpp:83:15: note: previous definition is here
  | using value_type = typename Source::value_type;
  | ^
  | 1 error generated.
```

Remove duplicate type definition(NFC).

---

include/jsoncons/utility/heap_string.hpp
include/jsoncons_ext/csv/csv_encoder.hpp
include/jsoncons_ext/ubjson/ubjson_parser.hpp

```
jsoncons_ext/csv/csv_encoder.hpp:202:22: error: use of undeclared identifier
'csv_errc'; did you mean 'conv_errc'?
202 |                 ec = csv_errc::source_error;
|                      ^~~~~~~~
|                      conv_errc
```
```
external/jsoncons+/include/jsoncons_ext/ubjson/ubjson_parser.hpp:512:39: error: 'is_base10' is not a member of 'jsoncons::detail'
--
  | 512 \|                 if (jsoncons::detail::is_base10(text_buffer_.data(),text_buffer_.length()))
  | \|                                       ^~~~~~~~~
```
```
external/jsoncons~/include/jsoncons/utility/heap_string.hpp: In member function 'const char_type* jsoncons::utility::heap_string<CharT, Extra, Allocator>::c_str() const':
--
  | external/jsoncons~/include/jsoncons/utility/heap_string.hpp:73:49: error: …
```

fix various header issue(NFC)

---

include/jsoncons/utility/bigint.hpp

Fixed a warning about possible misuse of comma in the while() with casting it to void.

Fixed warning

---

include/jsoncons/basic_json.hpp

Fixes the following clang 20 error:
```
jsoncons/basic_json.hpp:5571:34: error: identifier '_ojson' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
```

Fixes for clang 20

---

CMakeLists.txt
examples/build/cmake/CMakeLists.txt
test/CMakeLists.txt

I've updated the usage of CMake policy to set policies up to CMake 3.14, and made a couple of tweaks to comply with future policies as well.
I didn't go any further than 3.14, as some MSVC-specific policies are included in 3.15, and  I do not have a Windows development environment on which to test them.
Additionally, I was not able to actually test the examples, as it seems the `CMakeLists.txt` tries to import some nonexistent CMake files, but I'm confident that my changes there are appropriate nonetheless.
Solves #609

Update CMake policy usage to 3.14

---

test/jsonpatch/src/jsonpatch_tests.cpp

* "add" specifically states that the entire document gets replaced with "value" (https://datatracker.ietf.org/doc/html/rfc6902#section-4.1)
* "move", "replace", "test" and "copy" do not disallow operating on the root
* "remove" does not say anything about the root either. I would say that it should be an error, since there is no such thing as an "empty" JSON document
I expect that some of these test cases will fail the pipeline. Would need to take a closer look at the bug, but it looks like the code is treating "" (the root) as "/" (the "" key).

add test cases for jsonpatch where the jsonpointer "" (document root) is involved
